# docker-compose.yml
services:
  api:
    build: .
    container_name: home-pie-api
    restart: unless-stopped
    ports:
      - "7979:7979"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - /opt/projects/time-in-progress-socials:/app
    environment:
      - DATA_DIR=/data
    env_file:
      - .env