# Generated by Django 5.2.4 on 2025-11-17 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('led_address_start', models.IntegerField(default=0)),
                ('led_address_end', models.IntegerField(default=0)),
                ('led_count', models.IntegerField(default=8)),
                ('max_quantity', models.PositiveIntegerField(default=10)),
                ('low_quantity_threshold', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.compartment')),
            ],
        ),
        migrations.CreateModel(
            name='LEDConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_color', models.CharField(default='#00FF00', max_length=7)),
                ('low_quantity_color', models.CharField(default='#FF0000', max_length=7)),
                ('selected_color', models.CharField(default='#0000FF', max_length=7)),
                ('pulse', models.BooleanField(default=False)),
                ('blink', models.BooleanField(default=False)),
                ('compartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='led_config', to='inventory.compartment')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('tolerance', models.CharField(blank=True, max_length=20)),
                ('voltage_rating', models.CharField(blank=True, max_length=20)),
                ('package_type', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compartments', models.ManyToManyField(related_name='parts', through='inventory.Inventory', to='inventory.compartment')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part'),
        ),
        migrations.AddField(
            model_name='compartment',
            name='storage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='inventory.storageunit'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('part', 'compartment')},
        ),
    ]
